addSbtPlugin("pl.project13.scala" % "sbt-jmh"             % "0.2.20"   )
addSbtPlugin("org.scoverage"      % "sbt-scoverage"       % "1.5.0"    )
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager" % "1.1.4"    )
addSbtPlugin("org.wartremover"    % "sbt-wartremover"     % "1.2.1"    )
addSbtPlugin("com.github.gseitz"  % "sbt-release"         % "1.0.3"    )
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"         % "0.3.0"   )
